name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Create test result
        id: test-result
        uses: actions/github-script@v5
        with:
          script: |
            const { checks } = require('@actions/github');
            const conclusion = ${{ job.status == 'success' ? 'success' : 'failure' }};
            const check = await checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Test Results',
              head_sha: context.sha,
              status: 'completed',
              conclusion: conclusion,
              completed_at: new Date().toISOString(),
              output: {
                title: 'Test Results',
                summary: 'Tests have ' + conclusion,
              },
            });
            console.log(`::set-output name=check_id::${check.data.id}`);

      - name: Fail if tests fail
        if: steps.test-result.outputs.check_id != ''
        run: exit 1
