name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: frontend

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci
      
      - name: Checkout Backend Code
        uses: actions/checkout@v2
        with:
          repository: hicheem/restaurant-website-backend
          path: backend
          ref: main
          token: ${{ secrets.BACKEND_PAT }}

      - name: Install Backend Dependencies

        run: |
          cd backend
          npm ci

      - name: Start Backend
        run: |
          cd backend
          npm start &
          sleep 20 # give server some time to start
        env:
          PORT: 3007
          
      - name: Run tests
        continue-on-error: false
        run: |
          cd frontend
          npm test
        # run: npm test
        env:
          REACT_APP_ENVIRONMENT: ${{ vars.REACT_APP_ENVIRONMENT }}
          REACT_APP_DEVPM: ${{ secrets.REACT_APP_DEVPM }}

      # - name: Check if tests passed
      #   run: |
      #     exit_code=$(npm test)
      #     if [ $exit_code -ne 0 ]; then
      #       echo "Tests failed"
      #       exit 1
      #     fi

      # - name: Prevent push if tests failed
      #   continue-on-error: false
      #   run: |
      #     echo "Tests failed, preventing push"
      #     exit 1
