name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Check if tests passed
        run: |
          exit_code=$(npm test)
          if [ $exit_code -ne 0 ]; then
            echo "Tests failed"
            exit 1
          fi

      - name: Prevent push if tests failed
        continue-on-error: false
        run: |
          echo "Tests failed, preventing push"
          exit 1
